---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# tag-validate-action
name: 'ðŸ·ï¸ Unified Tag Validation'
description: >-
  Validates tags for versioning compliance (SemVer/CalVer) and cryptographic
  signatures (SSH/GPG)

inputs:
  tag_location:
    description: >-
      Path to tag - supports two formats:
      1. Remote: ORG/REPO/TAG
      (e.g., lfreleng-actions/tag-validate-action/v0.1.0)
      2. Local: PATH/TO/REPO/TAG (e.g., ./my-repo/v1.0.0)
      Local paths must contain a .git directory
    required: false
    default: ''
  tag_string:
    description: >-
      Tag string to validate (version format only, no signature check)
    required: false
    default: ''
  require_type:
    description: 'Required tag type (semver|calver|none)'
    required: false
    default: 'none'
  require_signed:
    description: 'Signature requirement (true|ssh|gpg|false|ambivalent)'
    required: false
    default: 'ambivalent'
  permit_missing:
    description: 'Allow missing tags without error'
    required: false
    default: 'false'
  token:
    description: >-
      GitHub token for authenticated API calls and private repository access
    required: false
    default: ''
  github_server_url:
    description: >-
      GitHub server URL for git operations (supports GitHub Enterprise Server).
      If not provided, falls back to GITHUB_SERVER_URL environment variable or
      https://github.com
    required: false
    default: ''
  debug:
    description: 'Enable debug output in action logs'
    required: false
    default: 'false'

outputs:
  valid:
    description: 'Set true if tag passes validation checks'
    value: ${{ steps.validate.outputs.valid }}
  tag_type:
    description: 'Detected tag type (semver|calver|both|unknown)'
    value: ${{ steps.validate.outputs.tag_type }}
  signing_type:
    # yamllint disable rule:line-length
    description: 'Detected signing type (gpg|ssh|unsigned|lightweight|invalid|gpg-unverifiable)'
    value: ${{ steps.validate.outputs.signing_type }}
  development_tag:
    description: 'Set true if development/pre-release tag detected'
    value: ${{ steps.validate.outputs.development_tag }}
  version_prefix:
    description: 'Set true if tag has version prefix (v or V)'
    value: ${{ steps.validate.outputs.version_prefix }}
  tag_name:
    description: 'The tag name being validated'
    value: ${{ steps.validate.outputs.tag_name }}

runs:
  using: 'composite'
  steps:
    # yamllint disable rule:line-length
    - name: 'Validate tag'
      id: validate
      shell: bash
      run: |
        # Call external validation script
        "${{ github.action_path }}/validate-tag.sh" \
          "${{ inputs.tag_location }}" \
          "${{ inputs.tag_string }}" \
          "${{ inputs.require_type }}" \
          "${{ inputs.require_signed }}" \
          "${{ inputs.permit_missing }}" \
          "${GITHUB_SERVER_URL_INPUT}" \
          "${{ inputs.debug }}" \
          "${{ github.repository }}"
      env:
        VALIDATION_TOKEN: ${{ inputs.token }}
        GITHUB_SERVER_URL_INPUT: ${{ inputs.github_server_url || env.GITHUB_SERVER_URL || 'https://github.com' }}
